# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-06 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='url',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(default='image?default.png', max_length=500, upload_to='img/%Y/%m'),
        ),
    ]
