# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-06 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sight', '0002_auto_20180706_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeixinToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(default='', max_length=500)),
                ('timestamp', models.CharField(default='', max_length=500)),
                ('nonce', models.CharField(default='', max_length=500)),
                ('echostr', models.CharField(default='', max_length=500)),
                ('token', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': '\u5fae\u4fe1Token',
                'verbose_name_plural': '\u5fae\u4fe1Token',
            },
        ),
    ]
