# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-06 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sight', '0003_weixintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('url', models.CharField(default='', max_length=500)),
                ('translate', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': '\u56fe\u7247\u4fe1\u606f',
                'verbose_name_plural': '\u56fe\u7247\u4fe1\u606f',
            },
        ),
    ]
